/**
 * 覆盖层 UI 模板（HTML 与 CSS）
 * 方向 C：悬浮球模式 —— 右下角悬浮球 + 按需弹出小面板
 */
const OVERLAY_HTML = [
'<div id="tokfree-overlay" class="tokfree-overlay tokfree-hidden">',
'  <div class="tokfree-header">',
'    <span class="tokfree-title">TokFree</span>',
'    <div class="tokfree-header-actions">',
'      <button id="tokfree-btn-theme" class="tokfree-btn-icon" title="切换亮色/暗色主题"><svg viewBox="0 0 24 24" width="15" height="15" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="display:block;pointer-events:none;"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/></svg></button>',
'      <button id="tokfree-btn-settings" class="tokfree-btn-icon" title="设置（低频功能收纳）"><svg viewBox="0 0 24 24" width="15" height="15" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="display:block;pointer-events:none;"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 1 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 1 1-2.83-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 1 1 2.83-2.83l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 1 1 2.83 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z"/></svg></button>',
'      <button id="tokfree-btn-minimize" class="tokfree-btn-icon" title="收起面板"><svg viewBox="0 0 24 24" width="15" height="15" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="display:block;pointer-events:none;"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg></button>',
'    </div>',
'  </div>',
'  <div class="tokfree-body">',
'    <div class="tokfree-section tokfree-token-section">',
'      <label class="tokfree-label">对话 Token</label>',
'      <div class="tokfree-token-display">',
'        <span id="tokfree-conv-token-count" class="tokfree-token-count">0</span>',
'        <span class="tokfree-token-unit">tokens</span>',
'        <button id="tokfree-btn-compact" class="tokfree-btn-compact" title="压缩上下文：生成摘要并分享最近对话，在新会话继续">压缩</button>',
'      </div>',
'      <div class="tokfree-auto-compact-row">',
'        <label class="tokfree-auto-compact-label"><input type="checkbox" id="tokfree-auto-compact-enabled" /> 自动压缩</label>',
'        <span class="tokfree-auto-compact-hint">超过</span>',
'        <input id="tokfree-auto-compact-threshold" type="number" min="1" max="1000" step="1" value="80" class="tokfree-auto-compact-input" />',
'        <span class="tokfree-auto-compact-hint">万 tokens 时触发</span>',
'        <button id="tokfree-auto-compact-save" class="tokfree-btn-compact" title="保存自动压缩设置">保存</button>',
'      </div>',
'    </div>',
'    <div class="tokfree-section tokfree-team-mode-section">',
'      <label class="tokfree-auto-compact-label"><input type="checkbox" id="tokfree-team-mode-toggle" /> 多 Agent 模式</label>',
'      <span class="tokfree-auto-compact-hint">开启后本窗口作为主大脑，可调度多个子 Agent 并行分工</span>',
'    </div>',
'    <div class="tokfree-section tokfree-project-dir-section">',
'      <div class="tokfree-project-dir-row">',
'        <span class="tokfree-label">当前项目目录</span>',
'        <button id="tokfree-btn-change-dir" class="tokfree-btn-change-dir" title="点击修改项目目录"><svg viewBox="0 0 24 24" width="13" height="13" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="display:block;pointer-events:none;"><polyline points="23 4 23 10 17 10"/><polyline points="1 20 1 14 7 14"/><path d="M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15"/></svg> 修改</button>',
'      </div>',
'      <div id="tokfree-project-dir-display" class="tokfree-project-dir-display">',
'        <span class="tokfree-dir-path">未选择</span>',
'      </div>',
'    </div>',
'    <div class="tokfree-divider"></div>',
'    <div class="tokfree-actions">',
'      <button id="tokfree-btn-quick-login" class="tokfree-btn tokfree-btn-primary tokfree-hidden" title="用账号池中的账号一键登录">一键登录</button>',
'      <button id="tokfree-btn-init" class="tokfree-btn tokfree-btn-primary">初始化项目</button>',
'      <button id="tokfree-btn-window-manager" class="tokfree-btn tokfree-btn-secondary" title="管理窗口（新建/切换）">窗口管理</button>',
'      <button id="tokfree-btn-mcp" class="tokfree-btn tokfree-btn-secondary" title="管理 MCP 工具">MCP</button>',
'      <button id="tokfree-btn-knowledge" class="tokfree-btn tokfree-btn-secondary" title="管理知识库：技能与全局偏好">知识库</button>',
'      <button id="tokfree-btn-account-pool" class="tokfree-btn tokfree-btn-secondary" title="管理账号池：集中管理账号密码，供窗口复用">账号池</button>',
'      <button id="tokfree-btn-goal" class="tokfree-btn tokfree-btn-secondary" title="查看自驱循环目标进度">目标进度</button>',
'    </div>',
'    <div class="tokfree-divider"></div>',
'    <div class="tokfree-actions">',
      '<button id="tokfree-btn-gen-doc" class="tokfree-btn tokfree-btn-primary" title="让 AI 生成项目说明文档 (TOKFREE.md)">生成项目说明</button>',
'    </div>',
'    <div class="tokfree-actions">',
'      <button id="tokfree-btn-manual-parse" class="tokfree-btn tokfree-btn-secondary" title="AI 卡住/停顿时点这里，发送“继续”指令催它往下做">卡住了？点我</button>',
'    </div>',
'<div class="tokfree-divider"></div>',
'    <div class="tokfree-section tokfree-todo-section">',
'      <div class="tokfree-session-header">',
'        <span class="tokfree-label">任务清单 <span id="tokfree-todo-progress" class="tokfree-todo-progress"></span></span>',
'        <button id="tokfree-todo-refresh" class="tokfree-btn-refresh-sessions" title="刷新任务清单">刷新</button>',
'      </div>',
'      <div id="tokfree-todo-list" class="tokfree-todo-list">',
'        <div class="tokfree-session-empty">暂无任务</div>',
'      </div>',
'    </div>',
'<div class="tokfree-divider"></div>',
'    <div class="tokfree-section">',
'      <label class="tokfree-label">补充说明（AI 忙时自动排队，随回执一起发）</label>',
'      <textarea id="tokfree-user-input" class="tokfree-cmd-preview" rows="2" placeholder="输入内容，回车或点发送（AI 忙时自动排队）" style="resize:vertical;min-height:44px;"></textarea>',
'      <div class="tokfree-actions" style="margin-top:6px;">',
'        <button id="tokfree-user-send" class="tokfree-btn tokfree-btn-primary">发送</button>',
'        <span id="tokfree-user-queue-hint" class="tokfree-cfg-hint" style="align-self:center;"></span>',
'      </div>',
'    </div>',
'    <div class="tokfree-section tokfree-session-section">',
'      <div class="tokfree-session-header">',
'        <span class="tokfree-label">会话列表</span>',
'        <button id="tokfree-btn-refresh-sessions" class="tokfree-btn-refresh-sessions" title="刷新会话列表"><svg viewBox="0 0 24 24" width="13" height="13" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="display:block;pointer-events:none;"><polyline points="23 4 23 10 17 10"/><polyline points="1 20 1 14 7 14"/><path d="M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15"/></svg> 刷新</button>',
'      </div>',
'      <div id="tokfree-session-list" class="tokfree-session-list">',
'        <div class="tokfree-session-empty">暂无会话</div>',
'      </div>',
'    </div>',
'    <div class="tokfree-divider"></div>',
'    <div class="tokfree-section">',
'      <label class="tokfree-label">发送延迟设置</label>',
'      <div style="display:flex;gap:8px;align-items:center;">',
'        <input id="tokfree-delay-min" type="number" min="0" max="10000" step="100" value="2000" style="width:70px;background:var(--ck-code-bg);border:1px solid var(--ck-border);border-radius:6px;padding:4px 8px;color:var(--ck-text);font-size:12px;" />',
'        <span style="color:var(--ck-text-dim);font-size:12px;">至</span>',
'        <input id="tokfree-delay-max" type="number" min="0" max="10000" step="100" value="4000" style="width:70px;background:var(--ck-code-bg);border:1px solid var(--ck-border);border-radius:6px;padding:4px 8px;color:var(--ck-text);font-size:12px;" />',
'        <span style="color:var(--ck-text-dim);font-size:12px;">ms</span>',
'      </div>',
'      <button id="tokfree-btn-save-delay" class="tokfree-btn-text" style="align-self:flex-end;">保存延迟设置</button>',
'    </div>',
'    <div class="tokfree-divider"></div>',
'    <div class="tokfree-section">',
'      <label class="tokfree-label">检测到任务：<span id="tokfree-task-status" class="tokfree-task-status tokfree-hidden"><span class="tokfree-spinner"></span>执行中</span></label>',
'      <pre id="tokfree-cmd-preview" class="tokfree-cmd-preview">暂无</pre>',
'    </div>',
'    <div id="tokfree-result-section" class="tokfree-section tokfree-hidden">',
'      <label class="tokfree-label">执行结果：</label>',
'      <div id="tokfree-result-status" class="tokfree-result-status"></div>',
'      <pre id="tokfree-result-output" class="tokfree-result-output"></pre>',
'    </div>',
'    <div class="tokfree-section">',
'      <details id="tokfree-history">',
'        <summary class="tokfree-label">历史记录</summary>',
'        <div id="tokfree-history-list" class="tokfree-history-list"></div>',
'        <button id="tokfree-btn-clear" class="tokfree-btn-text">清空历史</button>',
'      </details>',
'    </div>',
'  </div>',
'  <div class="tokfree-resize-handle ck-rs-se" id="tokfree-overlay-resize" data-corner="se" title="拖动缩放"></div>',
'  <div class="tokfree-resize-handle ck-rs-sw" data-corner="sw" title="拖动缩放"></div>',
'  <div class="tokfree-resize-handle ck-rs-ne" data-corner="ne" title="拖动缩放"></div>',
'  <div class="tokfree-resize-handle ck-rs-nw" data-corner="nw" title="拖动缩放"></div>',
'</div>',
'<div id="tokfree-settings-drawer" class="tokfree-settings-drawer tokfree-hidden">',
'<div class="tokfree-wm-header">',
'<span class="tokfree-title">设置</span>',
'<div class="tokfree-wm-header-actions">',
'<button id="tokfree-btn-save-settings" class="tokfree-btn tokfree-btn-primary tokfree-settings-save" title="保存设置">保存</button>',
'<button id="tokfree-settings-close" class="tokfree-btn-icon" title="关闭"><svg viewBox="0 0 24 24" width="15" height="15" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="display:block;pointer-events:none;"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg></button>',
'</div>',
'</div>',
'<div class="tokfree-wm-body">',
'    <div class="tokfree-section">',
'      <label class="tokfree-label">工具模式</label>',
'      <button id="tokfree-policy-mode" class="tokfree-btn tokfree-btn-secondary tokfree-policy-mode" title="点击切换 Plan/Act 模式">模式：Act（点击切 Plan）</button>',
'      <label class="tokfree-auto-compact-label"><input type="checkbox" id="tokfree-policy-trust" /> 信任模式（危险操作免确认）</label>',
'      <span class="tokfree-auto-compact-hint">信任模式与工具模式为全局设置，影响所有标签页（各标签可在发送框上方单独覆盖）</span>',
'      <span class="tokfree-auto-compact-hint">Plan 模式：AI 只读规划，写/执行操作会被阻止；Act 模式：正常执行，危险操作需确认</span>',
'    </div>',
'<div class="tokfree-divider"></div>',
'    <div class="tokfree-section">',
'      <label class="tokfree-label">通知</label>',
'      <label class="tokfree-auto-compact-label"><input type="checkbox" id="tokfree-set-notify" /> AI 完成时通知（窗口未聚焦时）</label>',
'    </div>',
'<div class="tokfree-divider"></div>',
'    <div class="tokfree-section">',
'      <label class="tokfree-label">软件更新</label>',
'      <button id="tokfree-btn-check-update" class="tokfree-btn tokfree-btn-secondary">检查更新</button>',
'      <span class="tokfree-auto-compact-hint">点击后若有新版本会提示下载</span>',
'    </div>',
'<div class="tokfree-divider"></div>',
'    <div class="tokfree-section">',
'      <label class="tokfree-label">失败自动重试</label>',
'      <label class="tokfree-auto-compact-label"><input type="checkbox" id="tokfree-set-retry" /> 请求失败自动重发（网络错误/429）</label>',
'      <div style="display:flex;gap:8px;align-items:center;margin-top:4px;">',
'        <span class="tokfree-auto-compact-hint">普通失败上限</span>',
'        <input id="tokfree-set-retry-count" type="number" min="-1" max="100" value="10" class="tokfree-auto-compact-input" />',
'        <span class="tokfree-auto-compact-hint">次</span>',
'      </div>',
'    </div>',
'<div class="tokfree-divider"></div>',
'    <div class="tokfree-section">',
'      <label class="tokfree-label">工具循环看门狗</label>',
'      <div style="display:flex;gap:8px;align-items:center;">',
'        <span class="tokfree-auto-compact-hint">等待超时</span>',
'        <input id="tokfree-set-wd-timeout" type="number" min="0" max="1800" value="300" class="tokfree-auto-compact-input" style="width:52px;" />',
'        <span class="tokfree-auto-compact-hint">秒</span>',
'      </div>',
'      <span class="tokfree-auto-compact-hint">AI 进入工具循环后，超时未回复则发「请继续」催促（0=禁用）</span>',
'    </div>',
'<div class="tokfree-divider"></div>',
'    <div class="tokfree-section">',
'      <label class="tokfree-label">生命监护</label>',
'      <label class="tokfree-auto-compact-label"><input type="checkbox" id="tokfree-set-guard" /> 启用（AI 停顿自动唤醒）</label>',
'    </div>',
'<div class="tokfree-divider"></div>',
'    <div class="tokfree-section">',
'      <label class="tokfree-label">自进化飞轮</label>',
'      <label class="tokfree-auto-compact-label"><input type="checkbox" id="tokfree-set-evolution" /> 启用（含引导者 / 自驱循环 / 自动进化）</label>',
'      <span class="tokfree-auto-compact-hint">关闭后，以下三个无人干预进程全部停止：引导者（战略巡检）、自驱循环驱动器、自动进化调度器。默认关闭。</span>',
'    </div>',
'<div class="tokfree-divider"></div>',
'    <div class="tokfree-section">',
'      <label class="tokfree-label">引导者（战略巡检）</label>',
'      <label class="tokfree-auto-compact-label"><input type="checkbox" id="tokfree-set-curator" /> 启用（系统空闲时自动发起战略思考）</label>',
'      <div style="display:flex;gap:8px;align-items:center;margin-top:4px;">',
'        <span class="tokfree-auto-compact-hint">空闲满</span>',
'        <input id="tokfree-set-curator-idle" type="number" min="1" max="1440" value="30" class="tokfree-auto-compact-input" style="width:56px;" />',
'        <span class="tokfree-auto-compact-hint">分钟后触发（分钟）</span>',
'      </div>',
'      <div style="display:flex;gap:8px;align-items:center;margin-top:4px;">',
'        <span class="tokfree-auto-compact-hint">两次巡检最小间隔</span>',
'        <input id="tokfree-set-curator-gap" type="number" min="1" max="1440" value="60" class="tokfree-auto-compact-input" style="width:56px;" />',
'        <span class="tokfree-auto-compact-hint">分钟</span>',
'      </div>',
'      <div style="display:flex;gap:8px;align-items:center;margin-top:4px;">',
'        <span class="tokfree-auto-compact-hint">建议目标数</span>',
'        <input id="tokfree-set-curator-props" type="number" min="1" max="10" value="3" class="tokfree-auto-compact-input" style="width:56px;" />',
'        <span class="tokfree-auto-compact-hint">个</span>',
'      </div>',
'      <label class="tokfree-auto-compact-label" style="margin-top:6px;">采集信号：</label>',
'      <div style="display:flex;flex-wrap:wrap;gap:10px;">',
'        <label class="tokfree-auto-compact-label"><input type="checkbox" id="tokfree-cur-col-git" /> Git</label>',
'        <label class="tokfree-auto-compact-label"><input type="checkbox" id="tokfree-cur-col-todos" /> TODO</label>',
'        <label class="tokfree-auto-compact-label"><input type="checkbox" id="tokfree-cur-col-lessons" /> 教训</label>',
'        <label class="tokfree-auto-compact-label"><input type="checkbox" id="tokfree-cur-col-skills" /> 技能</label>',
'        <label class="tokfree-auto-compact-label"><input type="checkbox" id="tokfree-cur-col-goals" /> 历史目标</label>',
'      </div>',
'      <textarea id="tokfree-set-curator-prompt" class="tokfree-cmd-preview" rows="2" placeholder="附加指令（可选）：追加到巡检简报末尾，引导 AI 的思考方向" style="resize:vertical;margin-top:6px;"></textarea>',
'      <div class="tokfree-actions" style="margin-top:6px;">',
'        <button id="tokfree-btn-curator-now" class="tokfree-btn tokfree-btn-secondary" title="立即发起一次战略巡检（不等空闲）">立即巡检一次</button>',
'      </div>',
'      <span id="tokfree-curator-hint" class="tokfree-auto-compact-hint"></span>',
'    </div>',
'<div class="tokfree-divider"></div>',
'    <div class="tokfree-section">',
'      <label class="tokfree-label">本地 OpenAI 兼容 API</label>',
'      <label class="tokfree-auto-compact-label"><input type="checkbox" id="tokfree-set-apiserver" /> 启用（将各窗口网页 AI 暴露为本地接口）</label>',
'      <div style="display:flex;gap:8px;align-items:center;margin-top:4px;">',
'        <span class="tokfree-auto-compact-hint">端口</span>',
'        <input id="tokfree-set-apiserver-port" type="number" min="1" max="65535" value="8788" class="tokfree-auto-compact-input" style="width:72px;" />',
'      </div>',
'      <span id="tokfree-apiserver-status" class="tokfree-auto-compact-hint">未启用</span>',
'      <span class="tokfree-auto-compact-hint">默认关闭。启用后可用 GET /v1/models 与 POST /v1/chat/completions（支持 stream）。</span>',
'    </div>',
'<div class="tokfree-divider"></div>',
'    <div class="tokfree-section">',
'      <label class="tokfree-label">ShardX 反检测浏览器</label>',
'      <span id="tokfree-shardx-status" class="tokfree-auto-compact-hint">查询中…</span>',
'      <span class="tokfree-auto-compact-hint">首次启动自动就位（静默安装 Launcher + 就位 MCP），无需手动配置。</span>',
'    </div>',
'<div class="tokfree-divider"></div>',
'    <div class="tokfree-section">',
'      <label class="tokfree-label">沉浸式交流</label>',
'      <button id="tokfree-btn-immersive" class="tokfree-btn tokfree-btn-secondary tokfree-btn-inline" title="切换为沉浸式交流模式">沉浸式交流</button>',
'    </div>',
'<div class="tokfree-divider"></div>',
'    <div class="tokfree-section">',
'      <label class="tokfree-label">磁盘清理</label>',
'      <div id="tokfree-disk-usage" class="tokfree-cfg-hint" style="margin-bottom:6px;">点击下方按钮查看占用</div>',
'      <div class="tokfree-actions">',
'        <button id="tokfree-btn-cleanup-cache" class="tokfree-btn tokfree-btn-secondary" title="删除浏览器缓存（保留登录态，需先关闭对应窗口）">清理缓存</button>',
'        <button id="tokfree-btn-cleanup-all" class="tokfree-btn tokfree-btn-secondary" title="清理孤儿数据：已删窗口残留 + 旧截图 + 日志">全量清理</button>',
'      </div>',
'    </div>',
'<div class="tokfree-divider"></div>',
'    <div class="tokfree-actions">',
'      <button id="tokfree-btn-about" class="tokfree-btn tokfree-btn-secondary" title="关于 TokFree">关于</button>',
'    </div>',
'    </div>',
'</div>',
'<div id="tokfree-window-manager" class="tokfree-window-manager tokfree-hidden">',
'  <div class="tokfree-wm-header">',
'    <span class="tokfree-title">窗口管理</span>',
'    <button id="tokfree-wm-close" class="tokfree-btn-icon" title="关闭"><svg viewBox="0 0 24 24" width="15" height="15" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="display:block;pointer-events:none;"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg></button>',
'  </div>',
'  <div class="tokfree-wm-body">',
'    <div class="tokfree-actions">',
'      <button id="tokfree-wm-new-window" class="tokfree-btn tokfree-btn-primary">新建窗口</button>',
'    </div>',
'    <div class="tokfree-divider"></div>',
'    <div class="tokfree-section">',
'      <div class="tokfree-session-header">',
'        <span class="tokfree-label">看门狗（AI 生命监护）</span>',
'        <span id="tokfree-wd-state" class="tokfree-wd-state">…</span>',
'      </div>',
'      <div class="tokfree-wd-row">',
'        <button id="tokfree-wd-toggle" class="tokfree-btn tokfree-btn-secondary">暂停</button>',
'        <button id="tokfree-wd-wake" class="tokfree-btn tokfree-btn-secondary">立即唤醒</button>',
'        <button id="tokfree-wd-refresh" class="tokfree-btn-refresh-sessions" title="刷新状态"><svg viewBox="0 0 24 24" width="13" height="13" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="display:block;pointer-events:none;"><polyline points="23 4 23 10 17 10"/><polyline points="1 20 1 14 7 14"/><path d="M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15"/></svg></button>',
'      </div>',
'    </div>',
'    <div class="tokfree-divider"></div>',
'    <div class="tokfree-section">',
'      <div id="tokfree-wm-overview" class="tokfree-mc-overview"></div>',
'    </div>',
'    <div class="tokfree-section">',
'      <div class="tokfree-session-header">',
'        <span class="tokfree-label">窗口列表</span>',
'        <button id="tokfree-wm-refresh" class="tokfree-btn-refresh-sessions" title="刷新窗口列表"><svg viewBox="0 0 24 24" width="13" height="13" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="display:block;pointer-events:none;"><polyline points="23 4 23 10 17 10"/><polyline points="1 20 1 14 7 14"/><path d="M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15"/></svg> 刷新</button>',
'      </div>',
'      <div id="tokfree-window-list" class="tokfree-session-list">',
'        <div class="tokfree-session-empty">暂无窗口</div>',
'      </div>',
'    </div>',
'    <div class="tokfree-divider"></div>',
'    <div class="tokfree-section tokfree-stats-section">',
'      <div class="tokfree-session-header">',
'        <span class="tokfree-label">运行统计</span>',
'        <button id="tokfree-stats-log-btn" class="tokfree-btn-refresh-sessions" title="展开/收起最近 50 条事件日志">查看日志</button>',
'      </div>',
'      <div id="tokfree-stats-summary" class="tokfree-stats-summary">—</div>',
'      <div id="tokfree-stats-list" class="tokfree-stats-list">',
'        <div class="tokfree-session-empty">暂无数据</div>',
'      </div>',
'      <span class="tokfree-label">最近活动</span>',
'      <div id="tokfree-stats-events" class="tokfree-mc-events"></div>',
'      <div id="tokfree-stats-log" class="tokfree-stats-log tokfree-hidden"></div>',
'    </div>',
'    <div class="tokfree-divider"></div>',
'    <div class="tokfree-section tokfree-usage-section">',
'      <div class="tokfree-session-header">',
'        <span class="tokfree-label">用量统计</span>',
'        <button id="tokfree-usage-refresh" class="tokfree-btn-refresh-sessions" title="刷新用量统计">刷新</button>',
'      </div>',
'      <div id="tokfree-usage-summary" class="tokfree-usage-summary">—</div>',
'      <div id="tokfree-usage-list" class="tokfree-usage-list">',
'        <div class="tokfree-session-empty">暂无数据</div>',
'      </div>',
'    </div>',
'    <div class="tokfree-divider"></div>',
'    <div id="tokfree-profile-config" class="tokfree-section tokfree-hidden">',
'      <div class="tokfree-session-header">',
'        <span class="tokfree-label">窗口设置：<span id="tokfree-cfg-name"></span></span>',
'        <button id="tokfree-cfg-close" class="tokfree-btn-icon" title="收起"><svg viewBox="0 0 24 24" width="15" height="15" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="display:block;pointer-events:none;"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg></button>',
'      </div>',
'      <div class="tokfree-cfg-tabs">',
'        <button class="tokfree-cfg-tab tokfree-cfg-tab-active" data-tab="account">账号</button>',
'        <button class="tokfree-cfg-tab" data-tab="proxy">代理</button>',
'        <button class="tokfree-cfg-tab" data-tab="fingerprint">指纹</button>',
'      </div>',
'      <div class="tokfree-cfg-pane" data-pane="account">',
'        <input id="tokfree-cfg-acct-label" class="tokfree-cfg-input" placeholder="账号标签（如 账号A）" />',
'        <input id="tokfree-cfg-acct-email" class="tokfree-cfg-input" placeholder="邮箱 / 登录名（可选）" />',
'        <input id="tokfree-cfg-acct-group" class="tokfree-cfg-input" placeholder="分组（如 工作）" />',
'        <div class="tokfree-cfg-row">',
'          <select id="tokfree-cfg-acct-status" class="tokfree-cfg-input">',
'            <option value="active">正常</option>',
'            <option value="limited">限流</option>',
'            <option value="expired">过期</option>',
'            <option value="disabled">停用</option>',
'          </select>',
'          <input id="tokfree-cfg-acct-quota" type="number" class="tokfree-cfg-input" placeholder="配额上限（0=不限）" />',
'        </div>',
'        <button id="tokfree-cfg-acct-save" class="tokfree-btn tokfree-btn-primary">保存账号</button>',
'        <div class="tokfree-cfg-hint">绑定账号池账号（自动登录用）：</div>',
'        <select id="tokfree-cfg-acct-bind" class="tokfree-cfg-input"></select>',
'        <div class="tokfree-actions">',
'          <button id="tokfree-cfg-acct-relogin" class="tokfree-btn tokfree-btn-secondary">立即重登</button>',
'        </div>',
'      </div>',
'      <div class="tokfree-cfg-pane tokfree-hidden" data-pane="proxy">',
'        <div class="tokfree-cfg-hint">直接粘贴代理地址，自动识别（推荐）：</div>',
'        <input id="tokfree-cfg-proxy-paste" class="tokfree-cfg-input" placeholder="socks5://user:pass@1.2.3.4:1080 或 1.2.3.4:8080" />',
'        <div class="tokfree-actions">',
'          <button id="tokfree-cfg-proxy-parse" class="tokfree-btn tokfree-btn-secondary">解析填入</button>',
'        </div>',
'        <label class="tokfree-cfg-check"><input type="checkbox" id="tokfree-cfg-proxy-enabled" /> 启用代理（需重启窗口生效）</label>',
'        <div class="tokfree-cfg-row">',
'          <select id="tokfree-cfg-proxy-protocol" class="tokfree-cfg-input">',
'            <option value="http">HTTP</option>',
'            <option value="https">HTTPS</option>',
'            <option value="socks5">SOCKS5</option>',
'          </select>',
'          <input id="tokfree-cfg-proxy-host" class="tokfree-cfg-input" placeholder="主机" />',
'          <input id="tokfree-cfg-proxy-port" type="number" class="tokfree-cfg-input" placeholder="端口" />',
'        </div>',
'        <div class="tokfree-cfg-row">',
'          <input id="tokfree-cfg-proxy-user" class="tokfree-cfg-input" placeholder="用户名（可选）" />',
'          <input id="tokfree-cfg-proxy-pass" type="password" class="tokfree-cfg-input" placeholder="密码（可选）" />',
'        </div>',
'        <div class="tokfree-actions">',
'          <button id="tokfree-cfg-proxy-test" class="tokfree-btn tokfree-btn-secondary">测试连通</button>',
'          <button id="tokfree-cfg-proxy-save" class="tokfree-btn tokfree-btn-primary">保存代理</button>',
'        </div>',
'        <div id="tokfree-cfg-proxy-result" class="tokfree-cfg-hint"></div>',
'      </div>',
'      <div class="tokfree-cfg-pane tokfree-hidden" data-pane="fingerprint">',
'        <div class="tokfree-cfg-hint">点一下自动生成一套完整虚拟身份（系统/时区/语言/CPU/屏幕/显卡）：</div>',
'        <button id="tokfree-cfg-fp-random" class="tokfree-btn tokfree-btn-primary"><svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="display:block;pointer-events:none;"><rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="8.5" cy="8.5" r="1.2" fill="currentColor"/><circle cx="15.5" cy="15.5" r="1.2" fill="currentColor"/></svg> 一键生成随机身份</button>',
'        <div id="tokfree-cfg-fp-card" class="tokfree-cfg-card">尚未生成身份</div>',
'        <label class="tokfree-cfg-check"><input type="checkbox" id="tokfree-cfg-fp-enabled" /> 启用指纹伪装（需重启窗口生效）</label>',
'        <div class="tokfree-cfg-row">',
'          <select id="tokfree-cfg-fp-os" class="tokfree-cfg-input">',
'            <option value="">跟随系统</option>',
'            <option value="win">Windows</option>',
'            <option value="mac">macOS</option>',
'            <option value="linux">Linux</option>',
'          </select>',
'          <input id="tokfree-cfg-fp-tz" class="tokfree-cfg-input" placeholder="时区（如 Asia/Shanghai）" />',
'        </div>',
'        <div class="tokfree-cfg-row">',
'          <input id="tokfree-cfg-fp-lang" class="tokfree-cfg-input" placeholder="语言（如 zh-CN）" />',
'          <input id="tokfree-cfg-fp-cores" type="number" class="tokfree-cfg-input" placeholder="CPU 核数" />',
'        </div>',
'        <div class="tokfree-cfg-row">',
'          <input id="tokfree-cfg-fp-sw" type="number" class="tokfree-cfg-input" placeholder="屏宽" />',
'          <input id="tokfree-cfg-fp-sh" type="number" class="tokfree-cfg-input" placeholder="屏高" />',
'        </div>',
'        <div class="tokfree-actions">',
'          <button id="tokfree-cfg-fp-reseed" class="tokfree-btn tokfree-btn-secondary">换新身份（重随机 seed）</button>',
'          <button id="tokfree-cfg-fp-save" class="tokfree-btn tokfree-btn-primary">保存并应用（需重启窗口）</button>',
'        </div>',
'      </div>',
'    </div>',
'  </div>',
'</div>',
'<div id="tokfree-goal-manager" class="tokfree-window-manager tokfree-hidden">',
'  <div class="tokfree-wm-header">',
'    <span class="tokfree-title">目标进度</span>',
'    <button id="tokfree-goal-close" class="tokfree-btn-icon" title="关闭"><svg viewBox="0 0 24 24" width="15" height="15" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="display:block;pointer-events:none;"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg></button>',
'  </div>',
'  <div class="tokfree-wm-body">',
'    <div class="tokfree-actions">',
'      <button id="tokfree-goal-refresh" class="tokfree-btn tokfree-btn-secondary">刷新</button>',
'    </div>',
'    <div id="tokfree-goal-list" class="tokfree-goal-list">',
'      <div class="tokfree-session-empty">暂无目标</div>',
'    </div>',
'  </div>',
'</div>',
'<div id="tokfree-mcp-manager" class="tokfree-window-manager tokfree-hidden">',
'  <div class="tokfree-wm-header">',
'    <span class="tokfree-title">MCP 工具</span>',
'    <button id="tokfree-mcp-close" class="tokfree-btn-icon" title="关闭"><svg viewBox="0 0 24 24" width="15" height="15" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="display:block;pointer-events:none;"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg></button>',
'  </div>',
'  <div class="tokfree-wm-body tokfree-mcp-body">',
'    <div class="tokfree-mcp-left">',
'      <div class="tokfree-session-header">',
'        <span class="tokfree-label">已配置</span>',
'        <button id="tokfree-mcp-refresh" class="tokfree-btn-refresh-sessions" title="刷新"><svg viewBox="0 0 24 24" width="13" height="13" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="display:block;pointer-events:none;"><polyline points="23 4 23 10 17 10"/><polyline points="1 20 1 14 7 14"/><path d="M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15"/></svg></button>',
'      </div>',
'      <div id="tokfree-mcp-list" class="tokfree-session-list">',
'        <div class="tokfree-session-empty">暂无</div>',
'      </div>',
'    </div>',
'    <div class="tokfree-mcp-right">',
'      <textarea id="tokfree-mcp-json" class="tokfree-cmd-preview tokfree-mcp-json" rows="14" style="font-size:11px;" placeholder="{\n  \"mcpServers\": {\n    \"filesystem\": {\n      \"command\": \"npx\",\n      \"args\": [\"-y\", \"@modelcontextprotocol/server-filesystem\", \"C:/my-project\"]\n    }\n  }\n}"></textarea>',
'      <div class="tokfree-actions">',
'        <button id="tokfree-mcp-save" type="button" class="tokfree-btn tokfree-btn-primary">保存配置</button>',
'      </div>',
'    </div>',
'  </div>',
'</div>',
'<div id="tokfree-knowledge-manager" class="tokfree-window-manager tokfree-hidden">',
'  <div class="tokfree-wm-header">',
'    <span class="tokfree-title">知识库</span>',
'    <button id="tokfree-know-close" class="tokfree-btn-icon" title="关闭"><svg viewBox="0 0 24 24" width="15" height="15" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="display:block;pointer-events:none;"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg></button>',
'  </div>',
'  <div class="tokfree-wm-body tokfree-mcp-body">',
'    <div class="tokfree-mcp-left">',
'      <div class="tokfree-session-header">',
'        <span class="tokfree-label">技能列表</span>',
'        <button id="tokfree-know-refresh" class="tokfree-btn-refresh-sessions" title="刷新"><svg viewBox="0 0 24 24" width="13" height="13" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="display:block;pointer-events:none;"><polyline points="23 4 23 10 17 10"/><polyline points="1 20 1 14 7 14"/><path d="M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15"/></svg></button>',
'      </div>',
'      <div id="tokfree-know-list" class="tokfree-session-list">',
'        <div class="tokfree-session-empty">暂无技能</div>',
'      </div>',
'    </div>',
'    <div class="tokfree-mcp-right">',
'      <div id="tokfree-know-empty" class="tokfree-cfg-hint">左侧选择技能以查看/编辑正文</div>',
'      <input id="tokfree-know-name" class="tokfree-cfg-input tokfree-hidden" placeholder="技能名（字母/数字/下划线/连字符）" />',
'      <textarea id="tokfree-know-content" class="tokfree-cmd-preview tokfree-know-content" rows="14" placeholder="技能正文（Markdown）"></textarea>',
'      <div class="tokfree-actions">',
'        <button id="tokfree-know-save" type="button" class="tokfree-btn tokfree-btn-primary tokfree-hidden">保存技能</button>',
'        <button id="tokfree-know-create" type="button" class="tokfree-btn tokfree-btn-secondary">新建技能</button>',
'      </div>',
'      <div class="tokfree-actions">',
'        <button id="tokfree-know-toggle-enabled" type="button" class="tokfree-btn tokfree-btn-secondary tokfree-hidden">启用/禁用（本项目）</button>',
'        <button id="tokfree-know-delete" type="button" class="tokfree-btn tokfree-btn-secondary tokfree-hidden">删除</button>',
'      </div>',
'      <div class="tokfree-divider"></div>',
'      <label class="tokfree-label">全局偏好（跨项目生效）</label>',
'      <textarea id="tokfree-know-pref" class="tokfree-cmd-preview tokfree-know-pref" rows="6" placeholder="全局偏好（Markdown）"></textarea>',
'      <div class="tokfree-actions">',
'        <button id="tokfree-pref-save" type="button" class="tokfree-btn tokfree-btn-primary">保存偏好</button>',
'      </div>',
'    </div>',
'  </div>',
'</div>',
'<div id="tokfree-account-pool" class="tokfree-window-manager tokfree-hidden">',
'  <div class="tokfree-wm-header">',
'    <span class="tokfree-title">账号池</span>',
'    <button id="tokfree-acct-close" class="tokfree-btn-icon" title="关闭"><svg viewBox="0 0 24 24" width="15" height="15" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="display:block;pointer-events:none;"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg></button>',
'  </div>',
'  <div class="tokfree-wm-body tokfree-mcp-body">',
'    <div class="tokfree-mcp-left">',
'      <div class="tokfree-session-header">',
'        <span class="tokfree-label">账号列表</span>',
'        <button id="tokfree-acct-refresh" class="tokfree-btn-refresh-sessions" title="刷新"><svg viewBox="0 0 24 24" width="13" height="13" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="display:block;pointer-events:none;"><polyline points="23 4 23 10 17 10"/><polyline points="1 20 1 14 7 14"/><path d="M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15"/></svg></button>',
'      </div>',
'      <div id="tokfree-acct-list" class="tokfree-session-list">',
'        <div class="tokfree-session-empty">暂无账号</div>',
'      </div>',
'    </div>',
'    <div class="tokfree-mcp-right">',
'      <div id="tokfree-acct-empty" class="tokfree-cfg-hint">左侧选择账号以编辑，或直接填写下方表单新建</div>',
'      <input id="tokfree-acct-label" class="tokfree-cfg-input" placeholder="账号标签（如 账号A）" />',
'      <input id="tokfree-acct-username" class="tokfree-cfg-input" placeholder="登录名 / 邮箱" />',
'      <input id="tokfree-acct-password" type="password" class="tokfree-cfg-input" placeholder="密码（留空则不修改；本地加密存储）" />',
'      <div class="tokfree-cfg-row">',
'        <input id="tokfree-acct-provider" class="tokfree-cfg-input" placeholder="平台（如 deepseek）" />',
'        <input id="tokfree-acct-group" class="tokfree-cfg-input" placeholder="分组（可选）" />',
'      </div>',
'      <textarea id="tokfree-acct-note" class="tokfree-cmd-preview tokfree-acct-note" rows="3" placeholder="备注（可选）"></textarea>',
'      <div class="tokfree-actions">',
'        <button id="tokfree-acct-save" type="button" class="tokfree-btn tokfree-btn-primary">保存</button>',
'        <button id="tokfree-acct-new" type="button" class="tokfree-btn tokfree-btn-secondary">新建</button>',
'      </div>',
'      <div class="tokfree-actions">',
'        <button id="tokfree-acct-delete" type="button" class="tokfree-btn tokfree-btn-secondary tokfree-hidden">删除</button>',
'      </div>',
'    </div>',
'  </div>',
'</div>',
'<div id="tokfree-status-badge" title="TokFree 运行中">',
'  <span id="tokfree-status-dot"></span>',
'  <span class="tokfree-fab-icon">C</span>',
'</div>',
'<div id="tokfree-first-time-dialog" class="tokfree-first-time-dialog tokfree-hidden">',
'  <div class="tokfree-first-time-box">',
'    <button id="tokfree-btn-first-close" class="tokfree-btn-icon tokfree-first-time-close" title="关闭"><svg viewBox="0 0 24 24" width="15" height="15" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="display:block;pointer-events:none;"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg></button>',
'    <div class="tokfree-first-time-text">首次创建对话时，需要初始化项目，并选择一个项目目录，不然无法使用</div>',
'    <div class="tokfree-actions">',
'      <button id="tokfree-btn-first-init" class="tokfree-btn tokfree-btn-primary">初始化项目</button>',
'    </div>',
'  </div>',
'</div>',
].join('\n');

const OVERLAY_CSS = [
'/* 品牌主题：violet */',
'[data-brand="violet"] {',
'  --ck-primary: #7c6cff;',
'  --ck-primary-strong: #6a58ff;',
'  --ck-primary-rgb: 124, 108, 255;',
'  --ck-primary-text: #a8afff;',
'}',
'/* 品牌主题：ocean */',
'[data-brand="ocean"] {',
'  --ck-primary: #3b82f6;',
'  --ck-primary-strong: #2563eb;',
'  --ck-primary-rgb: 59, 130, 246;',
'  --ck-primary-text: #93c5fd;',
'}',
'/* 品牌主题：forest */',
'[data-brand="forest"] {',
'  --ck-primary: #10b981;',
'  --ck-primary-strong: #059669;',
'  --ck-primary-rgb: 16, 185, 129;',
'  --ck-primary-text: #6ee7b7;',
'}',
'/* 品牌主题：sunset */',
'[data-brand="sunset"] {',
'  --ck-primary: #f97316;',
'  --ck-primary-strong: #ea580c;',
'  --ck-primary-rgb: 249, 115, 22;',
'  --ck-primary-text: #fdba74;',
'}',
'/* ===== 任务中心状态卡片 / 活动列表 ===== */',
'.tokfree-mc-overview { display: flex; gap: 10px; }',
'.tokfree-mc-card { flex: 1; background: var(--ck-surface); border: 1px solid var(--ck-border); border-radius: 12px; padding: 10px 12px; text-align: center; }',
'.tokfree-mc-card .tokfree-mc-num { font-size: 22px; font-weight: 800; font-family: Consolas, monospace; color: var(--ck-primary-text); }',
'.tokfree-mc-card .tokfree-mc-lbl { font-size: 11px; color: var(--ck-text-dim); margin-top: 2px; }',
'.tokfree-mc-events { max-height: 26vh; overflow-y: auto; display: flex; flex-direction: column; gap: 3px; font-family: Consolas, monospace; font-size: 11px; }',
'.tokfree-mc-event { display: flex; gap: 6px; }',
'.tokfree-mc-event .t { color: var(--ck-text-faint); flex-shrink: 0; }',
'.tokfree-mc-event .k { color: var(--ck-green); flex-shrink: 0; }',
'.tokfree-mc-event .d { color: var(--ck-text-dim); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }',
':root, [data-theme="dark"] {',
'  --ck-bg: rgba(17, 19, 34, 0.98);',
'  --ck-bg-elevated: rgba(22, 24, 44, 0.96);',
'  --ck-surface: rgba(255, 255, 255, 0.04);',
'  --ck-surface-hover: rgba(255, 255, 255, 0.08);',
'  --ck-surface-subtle: rgba(255, 255, 255, 0.02);',
'  --ck-border: rgba(255, 255, 255, 0.08);',
'  --ck-primary: #8b93ff;',
'  --ck-primary-strong: #6d76ff;',
'  --ck-primary-rgb: 139, 147, 255;',
'  --ck-primary-text: #a8afff;',
'  --ck-text: #dde1ff;',
'  --ck-text-strong: #c8ccff;',
'  --ck-text-dim: #8a90b8;',
'  --ck-text-faint: #5d6280;',
'  --ck-green: #7fd6a3;',
'  --ck-green-bright: #a7f3c0;',
'  --ck-red: #ff6b7a;',
'  --ck-red-rgb: 255, 107, 122;',
'  --ck-yellow: #ffc107;',
'  --ck-code-bg: rgba(0, 0, 0, 0.35);',
'  --ck-on-primary: #ffffff;',
'  --ck-scroll-thumb: rgba(255, 255, 255, 0.15);',
'  --ck-scroll-thumb-hover: rgba(255, 255, 255, 0.25);',
'}',
'[data-theme=light] {',
'  --ck-bg: rgba(250, 249, 246, 0.98);',
'  --ck-bg-elevated: rgba(255, 255, 255, 0.98);',
'  --ck-surface: rgba(0, 0, 0, 0.03);',
'  --ck-surface-hover: rgba(0, 0, 0, 0.06);',
'  --ck-surface-subtle: rgba(0, 0, 0, 0.015);',
'  --ck-border: rgba(0, 0, 0, 0.09);',
'  --ck-primary: #10b981;',
'  --ck-primary-strong: #059669;',
'  --ck-primary-rgb: 16, 185, 129;',
'  --ck-primary-text: #047857;',
'  --ck-text: #1f2937;',
'  --ck-text-strong: #111827;',
'  --ck-text-dim: #6b7280;',
'  --ck-text-faint: #9ca3af;',
'  --ck-green: #10b981;',
'  --ck-green-bright: #047857;',
'  --ck-red: #ef4444;',
'  --ck-red-rgb: 239, 68, 68;',
'  --ck-yellow: #f59e0b;',
'  --ck-code-bg: rgba(0, 0, 0, 0.045);',
'  --ck-on-primary: #ffffff;',
'  --ck-scroll-thumb: rgba(0, 0, 0, 0.15);',
'  --ck-scroll-thumb-hover: rgba(0, 0, 0, 0.28);',
'}',
'.tokfree-overlay {',
'  position: fixed; bottom: 84px; right: 24px; width: 320px; height: 78vh; max-height: 78vh; min-height: 320px;',
'  background: var(--ck-bg);',
'  border: 1px solid var(--ck-border);',
'  border-radius: 16px;',
'  z-index: 2147483647;',
'  will-change: transform;',
'  display: flex; flex-direction: column;',
'  box-shadow: 0 12px 40px rgba(0, 0, 0, 0.45), 0 0 0 1px rgba(var(--ck-primary-rgb), 0.06);',
'  transition: opacity 0.22s ease, transform 0.22s ease;',
'  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Microsoft YaHei", sans-serif;',
'  color: var(--ck-text); font-size: 13px; line-height: 1.55;',
'  overflow: hidden;',
'}',
'.tokfree-overlay.tokfree-hidden { opacity: 0; pointer-events: none; transform: translateY(8px); }',
'.tokfree-overlay { display: none !important; pointer-events: none !important; visibility: hidden !important; }',
'.tokfree-header {',
'  display: flex; align-items: center; justify-content: space-between;',
'  padding: 12px 16px 10px; flex-shrink: 0;',
'  border-bottom: 1px solid var(--ck-border);',
'  background: var(--ck-surface-subtle);',
'}',
'.tokfree-header-actions { display: flex; align-items: center; gap: 6px; }',
'.tokfree-resize-handle {',
'  position: absolute; width: 14px; height: 14px; z-index: 10;',
'  background: linear-gradient(135deg, transparent 50%, var(--ck-border) 50%);',
'}',
'.tokfree-resize-handle:hover { background: linear-gradient(135deg, transparent 50%, rgba(var(--ck-primary-rgb), 0.6) 50%); }',
'.ck-rs-se { right: 0; bottom: 0; cursor: nwse-resize; border-bottom-right-radius: 16px; }',
'.ck-rs-sw { left: 0; bottom: 0; cursor: nesw-resize; border-bottom-left-radius: 16px; transform: scaleX(-1); }',
'.ck-rs-ne { right: 0; top: 0; cursor: nesw-resize; border-top-right-radius: 16px; transform: scaleY(-1); }',
'.ck-rs-nw { left: 0; top: 0; cursor: nwse-resize; border-top-left-radius: 16px; transform: scale(-1,-1); }',
'.tokfree-header-actions .tokfree-btn-icon { width: 26px; height: 26px; font-size: 14px; }',
'.tokfree-title { font-size: 14px; font-weight: 700; color: var(--ck-text-strong); letter-spacing: 0.4px; }',
'.tokfree-btn-icon {',
'  background: var(--ck-surface); border: 1px solid var(--ck-border); color: var(--ck-text-dim);',
'  cursor: pointer; font-size: 16px; width: 28px; height: 28px; border-radius: 8px;',
'  display: flex; align-items: center; justify-content: center; transition: all 0.2s;',
'  line-height: 1;',
'}',
'.tokfree-btn-icon:hover { background: var(--ck-surface-hover); color: var(--ck-on-primary); }',
'.tokfree-body { padding: 12px 14px; overflow-y: auto; flex: 1; display: flex; flex-direction: column; gap: 12px; }',
  '.tokfree-token-section { padding: 8px 12px; background: var(--ck-code-bg); border: 1px solid var(--ck-border); border-radius: 12px; }',
  '.tokfree-token-display { display: flex; align-items: baseline; gap: 6px; margin-top: 2px; }',
  '.tokfree-token-count { font-size: 20px; font-weight: 700; color: var(--ck-green-bright); font-family: "Consolas", monospace; }',
  '.tokfree-token-unit { font-size: 11px; color: var(--ck-text-dim); }',
  '.tokfree-btn-compact {',
  '  margin-left: auto; background: rgba(var(--ck-primary-rgb), 0.2); border: none;',
  '  color: var(--ck-primary-text); padding: 2px 8px; border-radius: 6px;',
  '  cursor: pointer; font-size: 11px; font-weight: 600; align-self: center;',
  '}',
  '.tokfree-btn-compact:hover { background: rgba(var(--ck-primary-rgb), 0.4); }',
  '.tokfree-btn-compact:disabled { opacity: 0.5; cursor: not-allowed; }',
  '.tokfree-auto-compact-row { display: flex; align-items: center; gap: 5px; margin-top: 6px; flex-wrap: wrap; }',
  '.tokfree-auto-compact-label { display: flex; align-items: center; gap: 3px; font-size: 11px; color: var(--ck-text-dim); cursor: pointer; }',
  '.tokfree-auto-compact-label input { cursor: pointer; }',
  '.tokfree-auto-compact-hint { font-size: 11px; color: var(--ck-text-dim); }',
  '.tokfree-auto-compact-input { width: 34px; background: var(--ck-code-bg); border: 1px solid var(--ck-border); border-radius: 6px; padding: 2px 4px; color: var(--ck-text); font-size: 11px; text-align: center; }',
'.tokfree-policy-section { padding: 8px 12px; background: var(--ck-code-bg); border: 1px solid var(--ck-border); border-radius: 12px; }',
'.tokfree-policy-mode { flex: 0 0 auto; align-self: flex-start; }',
'.tokfree-section { display: flex; flex-direction: column; gap: 8px; }',
'.tokfree-label { font-size: 11px; font-weight: 700; color: var(--ck-text-dim); text-transform: uppercase; letter-spacing: 1px; cursor: pointer; }',
'.tokfree-cmd-preview {',
'  background: var(--ck-code-bg); border: 1px solid var(--ck-border);',
'  border-radius: 12px; padding: 10px 12px;',
'  font-family: "Cascadia Code", "Fira Code", "Consolas", monospace;',
'  font-size: 12px; color: var(--ck-green-bright); line-height: 1.5;',
'  max-height: 140px; overflow: auto; white-space: pre-wrap; word-break: break-all; margin: 0;',
'}',
'.tokfree-actions { display: flex; gap: 8px; width: 100%; }',
'.tokfree-actions .tokfree-btn { flex: 1 1 auto; }',
'.tokfree-btn {',
'  flex: 1; padding: 9px 14px; border: 1px solid transparent; border-radius: 10px;',
'  font-size: 12.5px; font-weight: 600; cursor: pointer;',
'  transition: all 0.22s ease; letter-spacing: 0.3px;',
'}',
'.tokfree-btn:active { transform: scale(0.98); }',
'.tokfree-btn-inline { flex: 0 0 auto; width: auto; padding: 6px 14px; font-size: 12px; align-self: flex-start; }',
'.tokfree-btn-primary {',
'  background: linear-gradient(135deg, var(--ck-primary), var(--ck-primary-strong)); color: var(--ck-on-primary);',
'  box-shadow: 0 6px 18px rgba(109, 118, 255, 0.25);',
'}',
'.tokfree-btn-primary:hover { box-shadow: 0 8px 22px rgba(109, 118, 255, 0.4); transform: translateY(-1px); }',
'.tokfree-btn-primary:disabled { opacity: 0.5; cursor: not-allowed; transform: none; }',
'.tokfree-btn-secondary {',
'  background: var(--ck-surface); color: var(--ck-text-strong);',
'  border-color: var(--ck-border);',
'}',
'.tokfree-btn-secondary:hover { background: var(--ck-surface-hover); color: var(--ck-on-primary); border-color: rgba(var(--ck-primary-rgb), 0.4); }',
'.tokfree-btn-text {',
'  background: none; border: none; color: var(--ck-text-dim); padding: 4px 0;',
'  text-align: left; font-size: 11px; cursor: pointer; transition: color 0.2s;',
'}',
'.tokfree-btn-text:hover { color: var(--ck-red); }',
'.tokfree-result-status { font-size: 12px; font-weight: 600; padding: 2px 0; }',
'.tokfree-result-status.success { color: var(--ck-green); }',
'.tokfree-result-status.error { color: var(--ck-red); }',
'.tokfree-result-output {',
'  background: var(--ck-code-bg); border: 1px solid var(--ck-border);',
'  border-radius: 12px; padding: 10px 12px;',
'  font-family: "Cascadia Code", "Fira Code", "Consolas", monospace;',
'  font-size: 11.5px; color: var(--ck-text-strong); line-height: 1.5;',
'  max-height: 200px; overflow: auto; white-space: pre-wrap; word-break: break-all; margin: 0;',
'}',
'.tokfree-history-list { max-height: 140px; overflow-y: auto; display: flex; flex-direction: column; gap: 6px; }',
'.tokfree-history-item {',
'  background: var(--ck-surface); border-radius: 10px; padding: 8px 10px;',
'  font-size: 12px; cursor: pointer; transition: background 0.2s;',
'}',
'.tokfree-history-item:hover { background: rgba(var(--ck-primary-rgb), 0.18); }',
'.tokfree-history-item .tokfree-cmd-text {',
'  font-family: "Consolas", monospace; color: var(--ck-green-bright); font-size: 12px;',
'  display: block; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;',
'}',
'.tokfree-history-item .tokfree-cmd-status { font-size: 11px; margin-top: 2px; display: block; }',
'.tokfree-history-item .tokfree-cmd-status.success { color: var(--ck-green); }',
'.tokfree-history-item .tokfree-cmd-status.error { color: var(--ck-red); }',
'.tokfree-history-item .tokfree-cmd-time { font-size: 10px; color: var(--ck-text-faint); margin-top: 2px; display: block; }',
'#tokfree-mcp-manager { width: 780px; max-width: 90vw; }',
'#tokfree-knowledge-manager { width: 780px; max-width: 90vw; }',
'#tokfree-knowledge-manager .tokfree-mcp-body { flex-direction: row; gap: 14px; align-items: stretch; overflow: hidden; }',
'#tokfree-account-pool { width: 780px; max-width: 90vw; }',
'#tokfree-account-pool .tokfree-mcp-body { flex-direction: row; gap: 14px; align-items: stretch; overflow: hidden; }',
'.tokfree-acct-item { display: flex; align-items: center; justify-content: space-between; gap: 6px; }',
'.tokfree-acct-item.tokfree-acct-active { border-color: rgba(var(--ck-primary-rgb), 0.5); background: rgba(var(--ck-primary-rgb), 0.12); }',
'.tokfree-acct-name { color: var(--ck-text-strong); font-weight: 600; font-size: 12px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; flex: 1; min-width: 0; }',
'.tokfree-acct-sub { color: var(--ck-text-dim); font-size: 11px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }',
'.tokfree-acct-note { resize: vertical; min-height: 60px; }',
'.tokfree-know-item { display: flex; align-items: center; justify-content: space-between; gap: 6px; }',
'.tokfree-know-item.tokfree-know-active { border-color: rgba(var(--ck-primary-rgb), 0.5); background: rgba(var(--ck-primary-rgb), 0.12); }',
'.tokfree-know-name { color: var(--ck-text-strong); font-weight: 600; font-size: 12px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; flex: 1; min-width: 0; }',
'.tokfree-know-desc { color: var(--ck-text-dim); font-size: 11px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }',
'.tokfree-know-toggle { font-size: 11px; cursor: pointer; padding: 2px 6px; border-radius: 6px; flex-shrink: 0; }',
'.tokfree-know-toggle.on { color: var(--ck-green); }',
'.tokfree-know-toggle.off { color: var(--ck-text-faint); }',
'.tokfree-know-content { flex: 1; min-height: 32vh; resize: vertical; }',
'.tokfree-know-pref { resize: vertical; }',
'#tokfree-mcp-manager .tokfree-mcp-body { flex-direction: row; gap: 14px; align-items: stretch; overflow: hidden; }',
'.tokfree-mcp-left { width: 220px; flex-shrink: 0; display: flex; flex-direction: column; }',
'.tokfree-mcp-left .tokfree-session-list { flex: 1; max-height: none; overflow-y: auto; }',
'.tokfree-mcp-right { flex: 1; display: flex; flex-direction: column; gap: 10px; }',
'.tokfree-mcp-json { flex: 1; min-height: 55vh; resize: vertical; }',
'.tokfree-mcp-right .tokfree-btn { flex: 0 0 auto; align-self: flex-start; }',
'.tokfree-settings-drawer {',
'  position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%);',
'  z-index: 2147483647; width: 580px; max-width: 92vw; height: 78vh; max-height: 85vh;',
'  background: var(--ck-bg);',
'  border: 1px solid var(--ck-border); border-radius: 16px;',
'  display: flex; flex-direction: column; overflow: hidden;',
'  box-shadow: 0 16px 50px rgba(0, 0, 0, 0.55), 0 0 0 1px rgba(var(--ck-primary-rgb), 0.08);',
'  transition: opacity 0.22s ease, transform 0.22s ease;',
'  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Microsoft YaHei", sans-serif;',
'  color: var(--ck-text); font-size: 13px;',
'}',
'.tokfree-settings-drawer.tokfree-hidden { opacity: 0; pointer-events: none; transform: translate(-50%, -50%) scale(0.95); }',
'#tokfree-settings-drawer .tokfree-wm-header { cursor: move; }',
'#tokfree-settings-drawer .tokfree-wm-header button { cursor: pointer; }',
'#tokfree-settings-drawer .tokfree-wm-body { overflow-y: auto; overflow-x: hidden; }',
'.tokfree-wm-header-actions { display: flex; align-items: center; gap: 8px; }',
'.tokfree-settings-save { flex: 0 0 auto; padding: 5px 14px; font-size: 12px; border-radius: 8px; }',
'.tokfree-window-manager {',
'  position: fixed; top: 50%; left: calc(50% - 60px); transform: translate(-50%, -50%);',
'  z-index: 2147483647; width: 676px; height: 80vh; max-height: 85vh;',
'  background: var(--ck-bg);',
'  border: 1px solid var(--ck-border); border-radius: 16px;',
'  display: flex; flex-direction: column; overflow: hidden;',
'  box-shadow: 0 16px 50px rgba(0, 0, 0, 0.55), 0 0 0 1px rgba(var(--ck-primary-rgb), 0.08);',
'  transition: opacity 0.22s ease, transform 0.22s ease;',
'}',
'.tokfree-window-manager.tokfree-hidden { opacity: 0; pointer-events: none; transform: translate(-50%, -50%) scale(0.95); }',
'#tokfree-mcp-manager, #tokfree-knowledge-manager, #tokfree-account-pool { width: 780px; max-width: 92vw; }',
'.tokfree-wm-header {',
'  display: flex; align-items: center; justify-content: space-between;',
'  padding: 12px 16px 10px; flex-shrink: 0;',
'  border-bottom: 1px solid var(--ck-border);',
'  background: var(--ck-surface-subtle);',
'}',
'.tokfree-wm-body { padding: 12px 14px; overflow: hidden; flex: 1; display: flex; flex-direction: column; gap: 12px; }',
'#tokfree-window-manager .tokfree-wm-body { overflow-y: auto; overflow-x: hidden; }',
'#tokfree-window-manager .tokfree-wm-header { cursor: move; }',
'#tokfree-window-manager .tokfree-wm-header button { cursor: pointer; }',
'.tokfree-window-item {',
'  display: flex; align-items: center; justify-content: space-between;',
'  background: var(--ck-surface); border: 1px solid var(--ck-border);',
'  border-radius: 10px; padding: 10px 12px; cursor: pointer;',
'  transition: background 0.2s; font-size: 12px;',
'  gap: 8px;',
'}',
'.tokfree-window-item:hover { background: rgba(var(--ck-primary-rgb), 0.18); }',
'.tokfree-window-left { display: flex; align-items: center; gap: 6px; flex: 1; min-width: 0; }',
'.tokfree-window-item .tokfree-window-name { color: var(--ck-text-strong); font-weight: 600; flex-shrink: 0; }',
'.tokfree-window-item .tokfree-window-sep { color: var(--ck-text-faint); flex-shrink: 0; }',
'.tokfree-window-item .tokfree-window-status { color: var(--ck-text-dim); font-size: 11px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }',
'.tokfree-window-item .tokfree-window-stats { color: var(--ck-green); font-size: 11px; flex-shrink: 0; white-space: nowrap; }',
'.tokfree-wd-row { display: flex; gap: 6px; margin-top: 6px; align-items: center; }',
'.tokfree-wd-state { font-size: 11px; color: var(--ck-text-dim); }',
'.tokfree-wd-state.tokfree-wd-ok { color: var(--ck-green); }',
'.tokfree-wd-state.tokfree-wd-paused { color: var(--ck-yellow); }',
'.tokfree-wd-state.tokfree-wd-off { color: var(--ck-text-faint); }',
'.tokfree-window-del {',
'  color: var(--ck-red); cursor: pointer; font-size: 11px; padding: 2px 6px;',
'  border-radius: 6px; flex-shrink: 0; transition: all 0.2s;',
'}',
'.tokfree-window-del:hover { background: rgba(var(--ck-red-rgb), 0.18); color: var(--ck-on-primary); }',
'.tokfree-window-cfg { color: var(--ck-text-dim); cursor: pointer; font-size: 13px; padding: 2px 6px; border-radius: 6px; flex-shrink: 0; transition: all 0.2s; }',
'.tokfree-window-cfg:hover { background: rgba(var(--ck-primary-rgb), 0.18); color: var(--ck-text-strong); }',
'.tokfree-window-role { color: var(--ck-text-dim); cursor: pointer; font-size: 11px; padding: 2px 6px; border-radius: 6px; flex-shrink: 0; transition: all 0.2s; }',
'.tokfree-window-role:hover { background: rgba(var(--ck-primary-rgb), 0.18); color: var(--ck-text-strong); }',
'.tokfree-role-menu { position: fixed; z-index: 2147483648; background: var(--ck-surface); border: 1px solid var(--ck-border); border-radius: 8px; padding: 4px; box-shadow: 0 4px 16px rgba(0,0,0,0.3); display: flex; flex-direction: column; gap: 2px; min-width: 150px; }',
'.tokfree-goal-list { display: flex; flex-direction: column; gap: 8px; max-height: 60vh; overflow-y: auto; }',
'.tokfree-goal-item { background: var(--ck-surface); border: 1px solid var(--ck-border); border-radius: 10px; padding: 10px 12px; }',
'.tokfree-goal-head { display: flex; align-items: center; justify-content: space-between; gap: 8px; }',
'.tokfree-goal-title { color: var(--ck-text-strong); font-weight: 600; font-size: 12px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }',
'.tokfree-goal-status { font-size: 11px; flex-shrink: 0; font-weight: 600; }',
'.tokfree-goal-meta { color: var(--ck-text-dim); font-size: 11px; margin-top: 4px; }',
'.tokfree-goal-crits { margin-top: 6px; display: flex; flex-direction: column; gap: 3px; }',
'.tokfree-goal-crit { font-size: 11px; color: var(--ck-text); line-height: 1.4; }',
'.tokfree-goal-crit-empty { color: var(--ck-text-faint); }',
'.tokfree-role-menu-item { padding: 6px 10px; font-size: 12px; color: var(--ck-text-strong); border-radius: 6px; cursor: pointer; white-space: nowrap; }',
'.tokfree-role-menu-item:hover { background: rgba(var(--ck-primary-rgb), 0.18); }',
'.tokfree-role-menu-row { display: flex; gap: 6px; padding: 4px 6px; align-items: center; }',
'.tokfree-role-menu-select { flex: 1; min-width: 0; background: var(--ck-code-bg); border: 1px solid var(--ck-border); border-radius: 6px; padding: 4px 6px; color: var(--ck-text); font-size: 12px; }',
'.tokfree-window-item.active { border-color: rgba(var(--ck-primary-rgb), 0.5); background: rgba(var(--ck-primary-rgb), 0.12); }',
'#tokfree-window-list { max-height: 38vh; flex: 0 0 auto; min-height: 0; overflow-y: auto; }',
'#tokfree-window-list .tokfree-window-item { flex-shrink: 0; }',
'.tokfree-stats-section { background: var(--ck-surface); border-radius: 10px; padding: 8px 10px; border: 1px solid var(--ck-border); }',
'.tokfree-stats-summary { font-size: 11px; color: var(--ck-green-bright); font-family: "Consolas", monospace; padding: 2px 0; }',
'.tokfree-stats-list { max-height: 24vh; overflow-y: auto; margin-top: 4px; display: flex; flex-direction: column; gap: 4px; }',
'.tokfree-stats-row { display: flex; align-items: center; justify-content: space-between; gap: 8px; font-size: 11px; color: var(--ck-text-strong); }',
'.tokfree-stats-row .tokfree-stats-win { color: var(--ck-text-strong); font-weight: 600; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }',
'.tokfree-stats-row .tokfree-stats-nums { color: var(--ck-text-dim); flex-shrink: 0; white-space: nowrap; }',
'.tokfree-stats-log { max-height: 32vh; overflow-y: auto; margin-top: 6px; display: flex; flex-direction: column; gap: 3px; font-family: "Consolas", monospace; font-size: 11px; }',
'.tokfree-stats-log-item { display: flex; gap: 6px; color: var(--ck-text-strong); line-height: 1.4; }',
'.tokfree-stats-log-time { color: var(--ck-text-faint); flex-shrink: 0; }',
'.tokfree-stats-log-win { color: var(--ck-primary-text); flex-shrink: 0; max-width: 90px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }',
'.tokfree-stats-log-type { color: var(--ck-green); flex-shrink: 0; }',
'.tokfree-stats-log-detail { color: var(--ck-text-dim); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }',
'.tokfree-usage-section { background: var(--ck-surface); border-radius: 10px; padding: 8px 10px; border: 1px solid var(--ck-border); }',
'.tokfree-usage-summary { font-size: 11px; color: var(--ck-green-bright); font-family: "Consolas", monospace; padding: 2px 0; line-height: 1.5; }',
'.tokfree-usage-summary .tokfree-usage-range { color: var(--ck-primary-text); font-weight: 600; }',
'.tokfree-usage-list { max-height: 24vh; overflow-y: auto; margin-top: 4px; display: flex; flex-direction: column; gap: 4px; }',
'.tokfree-usage-row { display: flex; align-items: center; justify-content: space-between; gap: 8px; font-size: 11px; color: var(--ck-text-strong); }',
'.tokfree-usage-row .tokfree-usage-win { color: var(--ck-text-strong); font-weight: 600; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }',
'.tokfree-usage-row .tokfree-usage-nums { color: var(--ck-text-dim); flex-shrink: 0; white-space: nowrap; }',
'#tokfree-profile-config { max-height: none; }',
'.tokfree-cfg-tabs { display: flex; gap: 6px; margin-bottom: 8px; }',
'.tokfree-cfg-tab { background: transparent; border: 1px solid var(--ck-border); color: var(--ck-text-dim); border-radius: 8px; padding: 4px 12px; font-size: 12px; cursor: pointer; }',
'.tokfree-cfg-tab-active { background: rgba(var(--ck-primary-rgb), 0.18); color: var(--ck-text-strong); border-color: rgba(var(--ck-primary-rgb), 0.5); }',
'.tokfree-cfg-pane { display: flex; flex-direction: column; gap: 8px; }',
'.tokfree-cfg-row { display: flex; gap: 8px; }',
'.tokfree-cfg-input { flex: 1; min-width: 0; background: var(--ck-code-bg); border: 1px solid var(--ck-border); border-radius: 6px; padding: 6px 8px; color: var(--ck-text); font-size: 12px; }',
'.tokfree-cfg-check { display: flex; align-items: center; gap: 6px; font-size: 12px; color: var(--ck-text-strong); }',
'.tokfree-cfg-hint { font-size: 11px; color: var(--ck-text-dim); min-height: 14px; }',
'.tokfree-cfg-card { background: var(--ck-code-bg); border: 1px solid var(--ck-border); border-radius: 8px; padding: 10px 12px; font-size: 11px; color: var(--ck-text-strong); line-height: 1.7; white-space: pre-wrap; }',
'#tokfree-status-badge {',
'  position: fixed; bottom: 24px; right: 24px; z-index: 2147483647;',
'  width: 48px; height: 48px; border-radius: 50%;',
'  background: rgba(var(--ck-primary-rgb), 0.22); border: 1px solid rgba(var(--ck-primary-rgb), 0.4);',
'  will-change: transform;',
'  display: flex; align-items: center; justify-content: center; gap: 0;',
'  cursor: pointer;',
'  transition: background 0.2s, border-color 0.2s, transform 0.15s;',
'}',
'#tokfree-status-badge:hover { background: rgba(var(--ck-primary-rgb), 0.35); border-color: rgba(var(--ck-primary-rgb), 0.65); transform: scale(1.05); }',
'#tokfree-status-badge { display: none !important; pointer-events: none !important; visibility: hidden !important; }',
'#tokfree-status-dot {',
'  position: absolute; top: 6px; right: 6px;',
'  width: 9px; height: 9px; border-radius: 50%;',
'  background: var(--ck-green); animation: tokfree-pulse 2s infinite;',
'}',
'.tokfree-fab-icon {',
'  font-size: 22px; font-weight: 800; color: var(--ck-primary-text); line-height: 1;',
'  user-select: none;',
'}',
'.tokfree-toast {',
'  position: fixed; top: 18px; left: 50%; transform: translateX(-50%) translateY(-8px);',
'  z-index: 2147483648; min-width: 200px; max-width: 380px; text-align: center;',
'  background: var(--ck-bg-elevated); backdrop-filter: blur(18px);',
'  -webkit-backdrop-filter: blur(18px);',
'  border: 1px solid rgba(var(--ck-primary-rgb), 0.28); border-radius: 12px;',
'  padding: 10px 16px; font-size: 13px; color: var(--ck-text);',
'  box-shadow: 0 10px 30px var(--ck-code-bg);',
'  opacity: 0; pointer-events: none; transition: opacity 0.22s ease, transform 0.22s ease;',
'}',
'.tokfree-toast.show { opacity: 1; transform: translateX(-50%) translateY(0); }',
'.tokfree-task-status {',
'  display: inline-flex; align-items: center; gap: 5px;',
'  color: var(--ck-primary-text); font-size: 11px; font-weight: 600;',
'}',
'.tokfree-spinner {',
'  width: 11px; height: 11px; border-radius: 50%;',
'  border: 2px solid rgba(var(--ck-primary-rgb), 0.25); border-top-color: var(--ck-primary);',
'  animation: tokfree-spin 0.8s linear infinite;',
'}',
'@keyframes tokfree-spin { to { transform: rotate(360deg); } }',
'@keyframes tokfree-pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.35; } }',
'@keyframes tokfree-attention {',
'  0%, 100% { transform: scale(1); }',
'  10%, 30%, 50%, 70%, 90% { transform: scale(1.08); }',
'  20%, 40%, 60%, 80% { transform: scale(0.98); }',
'}',
'.tokfree-btn-attention {',
'  animation: tokfree-attention 1s ease-in-out 3;',
'  background: rgba(var(--ck-primary-rgb), 0.35) !important;',
'  color: var(--ck-on-primary) !important;',
'  border-color: rgba(var(--ck-primary-rgb), 0.6) !important;',
'}',
'.tokfree-hidden { display: none !important; }',
'.tokfree-home-mode .tokfree-header .tokfree-btn-icon,',
'.tokfree-home-mode .tokfree-body .tokfree-section,',
'.tokfree-home-mode .tokfree-body .tokfree-actions:not(:has(#tokfree-btn-init)),',
'.tokfree-home-mode .tokfree-divider {',
'  display: none !important;',
'}',
// home 模式（无窗口/未初始化）：内容少，高度自适应，不留空白
'.tokfree-overlay.tokfree-home-mode { height: auto !important; max-height: 90vh !important; min-height: 0 !important; }',
'.tokfree-overlay.tokfree-home-mode .tokfree-body { flex: 0 0 auto; }',
'.tokfree-overlay ::-webkit-scrollbar, .tokfree-window-manager ::-webkit-scrollbar { width: 6px; }',
'.tokfree-overlay ::-webkit-scrollbar-track, .tokfree-window-manager ::-webkit-scrollbar-track { background: transparent; }',
'.tokfree-overlay ::-webkit-scrollbar-thumb, .tokfree-window-manager ::-webkit-scrollbar-thumb { background: var(--ck-scroll-thumb); border-radius: 3px; }',
'.tokfree-overlay ::-webkit-scrollbar-thumb:hover, .tokfree-window-manager ::-webkit-scrollbar-thumb:hover { background: var(--ck-scroll-thumb-hover); }',
'.tokfree-project-dir-section {',
'  background: var(--ck-surface); border-radius: 10px;',
'  padding: 8px 10px; border: 1px solid var(--ck-border);',
'}',
'.tokfree-project-dir-row { display: flex; justify-content: space-between; align-items: center; }',
'.tokfree-btn-change-dir {',
'  background: rgba(var(--ck-primary-rgb), 0.2); border: none;',
'  color: var(--ck-primary-text); padding: 2px 8px; border-radius: 6px;',
'  cursor: pointer; font-size: 11px; font-weight: 600;',
'}',
'.tokfree-btn-change-dir:hover { background: rgba(var(--ck-primary-rgb), 0.4); }',
'.tokfree-project-dir-display { margin-top: 4px; font-size: 12px; font-family: "Consolas", monospace; color: var(--ck-text-dim); word-break: break-all; }',
'.tokfree-dir-path { color: var(--ck-green-bright); }',
'.tokfree-divider { border-top: 1px solid var(--ck-border); margin: 2px 0; }',
'.tokfree-session-section {',
'  background: var(--ck-surface); border-radius: 10px;',
'  padding: 8px 10px; border: 1px solid var(--ck-border);',
'}',
'.tokfree-session-header { display: flex; justify-content: space-between; align-items: center; }',
'.tokfree-btn-refresh-sessions {',
'  background: rgba(var(--ck-primary-rgb), 0.2); border: none;',
'  color: var(--ck-primary-text); padding: 2px 8px; border-radius: 6px;',
'  cursor: pointer; font-size: 11px; font-weight: 600;',
'}',
'.tokfree-btn-refresh-sessions:hover { background: rgba(var(--ck-primary-rgb), 0.4); }',
'.tokfree-session-list { max-height: 100px; overflow-y: auto; margin-top: 4px; display: flex; flex-direction: column; gap: 4px; }',
'.tokfree-session-item { background: var(--ck-surface); border-radius: 8px; padding: 6px 10px; font-size: 12px; font-family: "Consolas", monospace; color: var(--ck-text); cursor: pointer; transition: background 0.2s; }',
'.tokfree-session-item:hover { background: rgba(var(--ck-primary-rgb), 0.2); }',
'.tokfree-session-item .session-id { color: var(--ck-primary-text); font-size: 11px; }',
'.tokfree-session-item .session-action { color: var(--ck-green-bright); font-size: 11px; font-weight: 600; }',
'.tokfree-session-empty { color: var(--ck-text-faint); font-size: 12px; font-style: italic; padding: 8px 0; text-align: center; }',
'.tokfree-todo-progress { color: var(--ck-text-dim); font-weight: 600; }',
'.tokfree-todo-list { max-height: 160px; overflow-y: auto; margin-top: 4px; display: flex; flex-direction: column; gap: 4px; }',
'.tokfree-todo-item { display: flex; gap: 6px; align-items: flex-start; font-size: 12px; line-height: 1.5; color: var(--ck-text); }',
'.tokfree-todo-icon { flex: 0 0 auto; width: 14px; text-align: center; color: var(--ck-text-dim); }',
'.tokfree-todo-text { flex: 1 1 auto; word-break: break-word; }',
'.tokfree-todo-item.tokfree-todo-active .tokfree-todo-icon { color: var(--ck-primary); }',
'.tokfree-todo-item.tokfree-todo-active .tokfree-todo-text { color: var(--ck-text-strong); font-weight: 600; }',
'.tokfree-todo-item.tokfree-todo-done .tokfree-todo-icon { color: var(--ck-green-bright); }',
'.tokfree-todo-item.tokfree-todo-done .tokfree-todo-text { color: var(--ck-text-faint); text-decoration: line-through; }',
'.tokfree-first-time-dialog {',
'  position: fixed; top: 0; left: 0; right: 0; z-index: 2147483647;',
'  display: flex; align-items: flex-start; justify-content: center;',
'  padding-top: 24px;',
'  pointer-events: none;',
'}',
'.tokfree-first-time-dialog.tokfree-hidden { display: none !important; }',
'.tokfree-first-time-box {',
'  position: relative; max-width: 420px; width: 90%;',
'  background: var(--ck-bg);',
'  border: 1px solid rgba(var(--ck-primary-rgb), 0.35);',
'  border-radius: 18px;',
'  padding: 28px 24px 22px;',
'  box-shadow: 0 20px 60px rgba(0, 0, 0, 0.6), 0 0 0 1px rgba(var(--ck-primary-rgb), 0.08);',
'  color: var(--ck-text); font-size: 14px; line-height: 1.6;',
'  text-align: center;',
'  pointer-events: auto;',
'}',
'.tokfree-first-time-close { position: absolute; top: 10px; right: 10px; }',
'.tokfree-first-time-text { margin-bottom: 18px; color: var(--ck-text); }',
'.tokfree-first-time-box .tokfree-actions { justify-content: center; }',
'.tokfree-first-time-box .tokfree-btn { flex: 0 0 auto; min-width: 150px; }',
  '.tokfree-retry-countdown {',
  '  position: fixed; bottom: 96px; right: 24px; z-index: 2147483647;',
  '  background: var(--ck-bg);',
  '  border: 1px solid rgba(var(--ck-primary-rgb), 0.35);',
  '  border-radius: 12px;',
  '  padding: 10px 14px;',
  '  box-shadow: 0 8px 30px rgba(0, 0, 0, 0.5), 0 0 0 1px rgba(var(--ck-primary-rgb), 0.08);',
  '  color: var(--ck-text); font-size: 13px;',
  '  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Microsoft YaHei", sans-serif;',
  '  transition: opacity 0.22s ease, transform 0.22s ease;',
  '}',
  '.tokfree-retry-countdown.tokfree-hidden { opacity: 0; pointer-events: none; transform: translateY(8px); }',
  '.tokfree-retry-countdown-inner { display: flex; align-items: center; gap: 12px; }',
  '#tokfree-retry-countdown-text { color: var(--ck-text); white-space: nowrap; }',
  '#tokfree-retry-cancel {',
  '  background: rgba(var(--ck-primary-rgb), 0.2); border: none;',
  '  color: var(--ck-primary-text); padding: 3px 10px; border-radius: 6px;',
  '  cursor: pointer; font-size: 12px; font-weight: 600;',
  '}',
  '#tokfree-retry-cancel:hover { background: rgba(var(--ck-red-rgb), 0.35); color: var(--ck-on-primary); }',
'.tokfree-role-badge { display: inline-block; padding: 0 5px; margin-left: 4px; font-size: 10px; font-weight: 700; border-radius: 4px; line-height: 16px; vertical-align: middle; }',
'.tokfree-role-master { background: rgba(124,108,255,0.22); color: #a8afff; border: 1px solid rgba(124,108,255,0.5); }',
'.tokfree-role-worker { background: rgba(127,214,163,0.18); color: #7fd6a3; border: 1px solid rgba(127,214,163,0.45); }',
'.tokfree-btn-icon-active { background: rgba(var(--ck-primary-rgb), 0.28) !important; color: var(--ck-primary-text) !important; }',
].join('\n');

module.exports = { OVERLAY_HTML, OVERLAY_CSS };
